/* Suggestion lists for autocomplete fields. Plain data, no logic. */

'use strict';

const COUNTRIES = "Afghanistan,Albania,Algeria,Andorra,Angola,Antigua and Barbuda,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahamas,Bahrain,Bangladesh,Barbados,Belarus,Belgium,Belize,Benin,Bhutan,Bolivia,Bosnia and Herzegovina,Botswana,Brazil,Brunei,Bulgaria,Burkina Faso,Burundi,Cabo Verde,Cambodia,Cameroon,Canada,Central African Republic,Chad,Chile,China,Colombia,Comoros,Costa Rica,Côte d'Ivoire,Croatia,Cuba,Cyprus,Czechia,Democratic Republic of the Congo,Denmark,Djibouti,Dominica,Dominican Republic,Ecuador,Egypt,El Salvador,Equatorial Guinea,Eritrea,Estonia,Eswatini,Ethiopia,Fiji,Finland,France,Gabon,Gambia,Georgia,Germany,Ghana,Greece,Grenada,Guatemala,Guinea,Guinea-Bissau,Guyana,Haiti,Honduras,Hungary,Iceland,India,Indonesia,Iran,Iraq,Ireland,Israel,Italy,Jamaica,Japan,Jordan,Kazakhstan,Kenya,Kiribati,Kosovo,Kuwait,Kyrgyzstan,Laos,Latvia,Lebanon,Lesotho,Liberia,Libya,Liechtenstein,Lithuania,Luxembourg,Madagascar,Malawi,Malaysia,Maldives,Mali,Malta,Marshall Islands,Mauritania,Mauritius,Mexico,Micronesia,Moldova,Monaco,Mongolia,Montenegro,Morocco,Mozambique,Myanmar,Namibia,Nauru,Nepal,Netherlands,New Zealand,Nicaragua,Niger,Nigeria,North Korea,North Macedonia,Norway,Oman,Pakistan,Palau,Palestine,Panama,Papua New Guinea,Paraguay,Peru,Philippines,Poland,Portugal,Qatar,Republic of the Congo,Romania,Russia,Rwanda,Saint Kitts and Nevis,Saint Lucia,Saint Vincent and the Grenadines,Samoa,San Marino,São Tomé and Príncipe,Saudi Arabia,Senegal,Serbia,Seychelles,Sierra Leone,Singapore,Slovakia,Slovenia,Solomon Islands,Somalia,South Africa,South Korea,South Sudan,Spain,Sri Lanka,Sudan,Suriname,Sweden,Switzerland,Syria,Taiwan,Tajikistan,Tanzania,Thailand,Timor-Leste,Togo,Tonga,Trinidad and Tobago,Tunisia,Turkey,Turkmenistan,Tuvalu,Uganda,Ukraine,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Vanuatu,Vatican City,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe".split(',');

const NATIONALITIES = "Afghan,Albanian,Algerian,American,Andorran,Angolan,Antiguan,Argentine,Armenian,Australian,Austrian,Azerbaijani,Bahamian,Bahraini,Bangladeshi,Barbadian,Basotho,Belarusian,Belgian,Belizean,Beninese,Bhutanese,Bolivian,Bosnian,Botswanan,Brazilian,British,Bruneian,Bulgarian,Burkinabé,Burundian,Cabo Verdean,Cambodian,Cameroonian,Canadian,Central African,Chadian,Chilean,Chinese,Colombian,Comoran,Congolese,Costa Rican,Croatian,Cuban,Cypriot,Czech,Danish,Djiboutian,Dominican,Dutch,Ecuadorian,Egyptian,Emirati,Equatorial Guinean,Eritrean,Estonian,Ethiopian,Fijian,Filipino,Finnish,French,Gabonese,Gambian,Georgian,German,Ghanaian,Greek,Grenadian,Guatemalan,Guinean,Guyanese,Haitian,Honduran,Hungarian,Icelandic,Indian,Indonesian,Iranian,Iraqi,Irish,Israeli,Italian,Ivorian,Jamaican,Japanese,Jordanian,Kazakhstani,Kenyan,Kittitian,Kosovar,Kuwaiti,Kyrgyz,Lao,Latvian,Lebanese,Liberian,Libyan,Liechtensteiner,Lithuanian,Luxembourgish,Macedonian,Malagasy,Malawian,Malaysian,Maldivian,Malian,Maltese,Marshallese,Mauritanian,Mauritian,Mexican,Micronesian,Moldovan,Monégasque,Mongolian,Montenegrin,Moroccan,Mozambican,Myanmar (Burmese),Namibian,Nauruan,Nepali,New Zealander,Nicaraguan,Nigerien,Nigerian,North Korean,Norwegian,Omani,Pakistani,Palauan,Palestinian,Panamanian,Papua New Guinean,Paraguayan,Peruvian,Polish,Portuguese,Qatari,Romanian,Russian,Rwandan,Saint Lucian,Salvadoran,Sammarinese,Samoan,São Toméan,Saudi,Senegalese,Serbian,Seychellois,Sierra Leonean,Singaporean,Slovak,Slovenian,Solomon Islander,Somali,South African,South Korean,South Sudanese,Spanish,Sri Lankan,Sudanese,Surinamese,Swazi,Swedish,Swiss,Syrian,Taiwanese,Tajik,Tanzanian,Thai,Timorese,Togolese,Tongan,Trinidadian,Tunisian,Turkish,Turkmen,Tuvaluan,Ugandan,Ukrainian,Uruguayan,Uzbek,Vanuatuan,Venezuelan,Vietnamese,Vincentian,Yemeni,Zambian,Zimbabwean".split(',');

const LANGUAGES = "English,Russian,Kazakh,Uzbek,Kyrgyz,Tajik,Turkmen,Ukrainian,Belarusian,Armenian,Georgian,Azerbaijani,Arabic,French,German,Spanish,Portuguese,Italian,Dutch,Polish,Czech,Slovak,Hungarian,Romanian,Bulgarian,Serbian,Croatian,Bosnian,Albanian,Macedonian,Greek,Turkish,Persian (Farsi),Dari,Pashto,Urdu,Hindi,Bengali,Punjabi,Chinese (Mandarin),Cantonese,Japanese,Korean,Vietnamese,Thai,Indonesian,Malay,Tagalog,Mongolian,Hebrew,Amharic,Swahili,Hausa,Yoruba,Zulu,Somali,Norwegian,Swedish,Danish,Finnish,Estonian,Latvian,Lithuanian,Icelandic".split(',');

const PROFICIENCY_LEVELS = ['Basic', 'Working', 'Fluent', 'Native'];
